name = "qq-music-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "qqmusicapi"
database_id = "52b7beff-8307-44a5-b4e6-c0980d60f8a9" 

# 定时刷新凭证 (每天凌晨 3 点)
[triggers]
crons = ["0 3 * * *"]


# 开启日志
[observability]
[observability.logs]
enabled = true
invocation_logs = true
